        
spring:
  datasource:
    url: jdbc:h2:mem:accountsdb
    driver-class-name: org.h2.Driver
    username: root
    password: 54321
    
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect 
    
build:
  version: 2.0    
               
  accounts:
  message: "Welcome to ZettaBank accounts related APIs"
  contactDetails:
    name: "Bhargav S - Developer"
    email: "bhargav.s@zettabank.in"
  onCallSupport:
    - 9887654787
    - 9988654317