build:
  version: 2.0.0    
accounts:
  message: "Welcome to ZettaBank accounts dev related APIs from git"
  contactDetails:
    name: "Bhargav S - Developer"
    email: "bhargav.s@zettabank.in"
  onCallSupport:
    - 9887654787
    - 9988654317
