build:
  version: 3.2    
accounts:
  message: "Welcome to ZettaBank accounts QA related APIs from git"
  contactDetails:
    name: "Bhargav S - QA"
    email: "bhargav.s@zettabank.in"
  onCallSupport:
    - 9887654788
    - 9988654318
